// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/hello.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RainServiceClient is the client API for RainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RainServiceClient interface {
	// Sends a greeting
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type rainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRainServiceClient(cc grpc.ClientConnInterface) RainServiceClient {
	return &rainServiceClient{cc}
}

func (c *rainServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/RainService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RainServiceServer is the server API for RainService service.
// All implementations must embed UnimplementedRainServiceServer
// for forward compatibility
type RainServiceServer interface {
	// Sends a greeting
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedRainServiceServer()
}

// UnimplementedRainServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRainServiceServer struct {
}

func (UnimplementedRainServiceServer) Hello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedRainServiceServer) mustEmbedUnimplementedRainServiceServer() {}

// UnsafeRainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RainServiceServer will
// result in compilation errors.
type UnsafeRainServiceServer interface {
	mustEmbedUnimplementedRainServiceServer()
}

func RegisterRainServiceServer(s grpc.ServiceRegistrar, srv RainServiceServer) {
	s.RegisterService(&RainService_ServiceDesc, srv)
}

func _RainService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RainServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RainService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RainServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RainService_ServiceDesc is the grpc.ServiceDesc for RainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RainService",
	HandlerType: (*RainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _RainService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello.proto",
}
