// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/mock.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MockServiceClient is the client API for MockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockServiceClient interface {
	StartMock(ctx context.Context, in *MockRequest, opts ...grpc.CallOption) (*MockReply, error)
	StopMock(ctx context.Context, in *MockRequest, opts ...grpc.CallOption) (*MockReply, error)
}

type mockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockServiceClient(cc grpc.ClientConnInterface) MockServiceClient {
	return &mockServiceClient{cc}
}

func (c *mockServiceClient) StartMock(ctx context.Context, in *MockRequest, opts ...grpc.CallOption) (*MockReply, error) {
	out := new(MockReply)
	err := c.cc.Invoke(ctx, "/MockService/startMock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) StopMock(ctx context.Context, in *MockRequest, opts ...grpc.CallOption) (*MockReply, error) {
	out := new(MockReply)
	err := c.cc.Invoke(ctx, "/MockService/stopMock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockServiceServer is the server API for MockService service.
// All implementations must embed UnimplementedMockServiceServer
// for forward compatibility
type MockServiceServer interface {
	StartMock(context.Context, *MockRequest) (*MockReply, error)
	StopMock(context.Context, *MockRequest) (*MockReply, error)
	mustEmbedUnimplementedMockServiceServer()
}

// UnimplementedMockServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMockServiceServer struct {
}

func (UnimplementedMockServiceServer) StartMock(context.Context, *MockRequest) (*MockReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMock not implemented")
}
func (UnimplementedMockServiceServer) StopMock(context.Context, *MockRequest) (*MockReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopMock not implemented")
}
func (UnimplementedMockServiceServer) mustEmbedUnimplementedMockServiceServer() {}

// UnsafeMockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockServiceServer will
// result in compilation errors.
type UnsafeMockServiceServer interface {
	mustEmbedUnimplementedMockServiceServer()
}

func RegisterMockServiceServer(s grpc.ServiceRegistrar, srv MockServiceServer) {
	s.RegisterService(&MockService_ServiceDesc, srv)
}

func _MockService_StartMock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).StartMock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MockService/startMock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).StartMock(ctx, req.(*MockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_StopMock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).StopMock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MockService/stopMock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).StopMock(ctx, req.(*MockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MockService_ServiceDesc is the grpc.ServiceDesc for MockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MockService",
	HandlerType: (*MockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "startMock",
			Handler:    _MockService_StartMock_Handler,
		},
		{
			MethodName: "stopMock",
			Handler:    _MockService_StopMock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mock.proto",
}
